* DHCP config

** Install isc-dhcp-server

#+BEGIN_SRC bash
sudo apt update
sudo apt install isc-dhcp-server
#+END_SRC

** Config interface that dhcp server listens on

 1. Run command =ifconfig= and take note of the interface name that has ip address =10.5.5.5=, e.g. =enp0s3=
 2. Edit =/etc/default/isc-dhcp-server= file to set the interface name.
   #+BEGIN_SRC bash
    INTERFACESv4="enp0s3"
    INTERFACESv6=""
   #+END_SRC

** Config dhcp server

1. Edit the main dhcp configuration file =/etc/dhcp/dhcpd.conf= and add the lines below:

  #+BEGIN_SRC bash
  option domain-name "isp5.lab";
  option domain-name-servers 10.5.5.5;

  default-lease-time 600;
  max-lease-time 7200;

  ddns-update-style none;

  authoritative;

  ## config the subnet for server network
  subnet 10.5.5.0 netmask 255.255.255.0 {
    range 10.5.5.100 10.5.5.200
    option domain-name-servers 10.5.5.5;
    option domain-name "isp5.lab";
    option subnet-mask 255.255.255.0;
    option routers 10.5.5.1;
    option broadcast-address 10.5.5.255;
    default-lease-time 600;
    max-lease-time 7200;
  }

  ## config the subnet for client network
  subnet 10.5.10.0 netmask 255.255.255.0 {
    range 10.5.10.100 10.5.10.200
    option domain-name-servers 10.5.5.5;
    option domain-name "isp5.lab";
    option subnet-mask 255.255.255.0;
    option routers 10.5.10.1;
    option broadcast-address 10.5.10.255;
    default-lease-time 600;
    max-lease-time 7200;
  }
  #+END_SRC

2. Start dhcp server
  #+BEGIN_SRC bash
   sudo systemctl start isc-dhcp-server
   # or
   sudo server isc-dhcp-server start
  #+END_SRC

3. Verify dhcp server status
  #+BEGIN_SRC bash
   sudo systemctl status isc-dhcp-server
  #+END_SRC

*** Troublshooting

if server status is not *active*, check the error logs by running command =view /var/log/syslog=.
And press =SHIFT + g= to scroll to the bottom of the file.

After having fixed the issue, restart dhcp server and verify status again.

** Install DHCP Relay on Router C

#+BEGIN_SRC bash
enable
config terminal
interface Gi 0/1

ip address-helper 10.5.5.5
do wr
#+END_SRC

** Verify

Once the DHCP server is up and running and DHCP relay is installed on Router C,
you can connect another computer to the client network and run the following command to verify.

#+BEGIN_SRC bash
sudo dhclient eth1
ifconfig # check if you got ip address between 10.5.10.100 and 10.5.10.200 on interface eth1.
#+END_SRC

=eth1= needs to be replaced with the actual client interface name.
There is no need to specify default gateway on client VM as it will receive from =dhcp= server.

*** Troubleshooting
Verify if default gateway was added on the server VM =route -n=.
Otherwise add it by =sudo route add default gateway 10.5.5.1=.


