version: "3.5"

services:
  namenode:
    image: id2221/hadoop-namenode
    container_name: namenode
    networks:
      - id2221
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - 9870:9870

  datanode:
    image: id2221/hadoop-datanode
    container_name: datanode
    networks:
      - id2221
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - 9864:9864

  resourcemanager:
    image: id2221/hadoop-resourcemanager
    container_name: resourcemanager
    networks:
      - id2221
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./hadoop/hadoop.env
    ports:
      - 8088:8088

  nodemanager1:
    image: id2221/hadoop-nodemanager
    container_name: nodemanager
    networks:
      - id2221
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop/hadoop.env

  historyserver:
    image: id2221/hadoop-historyserver
    container_name: historyserver
    networks:
      - id2221
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop/hadoop.env

  hbase:
    image: id2221/hbase-standalone
    container_name: hbase
    networks:
      - id2221
    volumes:
      - hbase_data:/hbase-data
      - hbase_zookeeper_data:/zookeeper-data
    ports:
      - 16000:16000
      - 16010:16010
      - 16020:16020
      - 16030:16030
      - 2888:2888
      - 3888:3888
      - 2181:2181
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    env_file:
      - ./hbase/hbase-standalone.env

networks:
  id2221:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  hbase_data:
  hbase_zookeeper_data:
