package se.sep.security.domain.model;

public enum Role {
  CUSTOMER_SERVICE_OFFICER,
  CUSTOMER_SERVICE_SENIOR_OFFICER,
  PRODUCTION_MANAGER,
  FINANCIAL_MANAGER,
  HR_MANAGER,
  ADMINISTRATION_MANAGER,
  EMPLOYEE
}
